<?php
declare(strict_types=1);

namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;


/**
 * LinkRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRequestRepository extends EntityRepository {
  /**
   * @param \DateTime $since
   * @return array
   */
  public function findRequestsSince(\DateTime $since) {
    // Build query
    $qb = $this->getEntityManager()
      ->createQueryBuilder()
      ->select('requests')
      ->from('AppBundle:LinkRequest', 'requests');
    $qb->where('requests.dateCreated >= :since')
      ->setParameter('since', $since);

    return $qb->getQuery()
      ->getResult();
  }
}
