<?php
declare(strict_types=1);

namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;


/**
 * LinkRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRequestRepository extends EntityRepository {
  /**
   * Finds shortened link by shortcut.
   *
   * @param string $shortcut
   * @return null|object
   */
  /*public function findOneByShortcut(string $shortcut) {
    return $this->findOneBy(['shortcut' => $shortcut, 'deleted' => FALSE]);
  }*/
}
