<?php
declare(strict_types=1);

namespace AppBundle\Repository;


use Doctrine\ORM\EntityRepository;


/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends EntityRepository {
  /**
   * Finds shortened link by shortcut.
   *
   * @param string $shortcut
   * @return null|object
   */
  public function findOneByShortcut(string $shortcut) {
    return $this->findOneBy(['shortcut' => $shortcut, 'deleted' => FALSE]);
  }

  /**
   * @param \DateTime $since
   * @return array
   */
  public function findLinksCreatedSince(\DateTime $since) {
    // Build query
    $qb = $this->getEntityManager()
      ->createQueryBuilder()
      ->select('links')
      ->from('AppBundle:Link', 'links');
    $qb->where('links.dateCreated >= :since')
      ->setParameter('since', $since);

    return $qb->getQuery()
      ->getResult();
  }
}
