<?php
declare(strict_types=1);

namespace AppBundle\Repository;


use AppBundle\NowDateHelper;
use Doctrine\ORM\EntityRepository;


/**
 * OwnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OwnerRepository extends EntityRepository {
  /**
   * Finds owner by api key.
   *
   * @param string $apiKey
   * @return null|object
   * @throws \Doctrine\ORM\NonUniqueResultException
   */
  public function findOneByApiKey(string $apiKey) {
    // Build query
    $qb = $this->getEntityManager()
      ->createQueryBuilder()
      ->select('owner')
      ->from('AppBundle:Owner', 'owner');
    $qb->where('owner.validUntil >= :deadline')
      ->andWhere('owner.apiKey = :apiKey')
      ->setParameter('deadline', NowDateHelper::getNow())
      ->setParameter('apiKey', $apiKey);

    return $qb->getQuery()
      ->getOneOrNullResult();
  }
}
